class DiseaseStates {
  final String name;
  final String prevalence;
  final String regions;
  final String causes;
  final String transmission;

  final double? prevalencePercent; // النسبة المئوية لانتشار المرض (تقريباً)
  final int? annualIncidence; // الإصابات السنوية الجديدة (عدد تقريبي)
  final int? affectedPopulation; // عدد الأشخاص المصابين تقريباً

  DiseaseStates({
    required this.name,
    required this.prevalence,
    required this.regions,
    required this.causes,
    required this.transmission,
    this.prevalencePercent,
    this.annualIncidence,
    this.affectedPopulation,
  });
}

final Map<String, List<DiseaseStates>> diseaseStates = {
  'en': [
    DiseaseStates(
      name: "Cerebral Palsy",
      prevalence: "About 2-3 per 1000 live births worldwide",
      regions: "Equally common in developed and developing countries",
      causes:
          "Brain injury before, during, or shortly after birth (oxygen deprivation, infection, trauma)",
      transmission: "Not contagious, caused by brain damage",
      prevalencePercent: 0.2,
      annualIncidence: 150000,
      // حوالي 150 ألف حالة جديدة سنوياً
      affectedPopulation: 17000000, // 17 مليون حالة حول العالم تقريباً
    ),
    DiseaseStates(
      name: "Multiple Sclerosis",
      prevalence: "More common in temperate regions",
      regions: "Northern Europe, North America, less common in tropical areas",
      causes:
          "Autoimmune disease with genetic and environmental factors (Vitamin D deficiency)",
      transmission: "Not contagious",
      prevalencePercent: 0.1,
      annualIncidence: 25000,
      affectedPopulation: 2500000,
    ),
    DiseaseStates(
      name: "Spinal Cord Injuries",
      prevalence: "250-500 new cases per million people annually",
      regions:
          "Varies by country, more common in areas with road accidents and sports injuries",
      causes: "Traffic accidents, sports injuries, falls",
      transmission: "Not contagious",
      prevalencePercent: null,
      annualIncidence: 180000,
      // تقدير عالمي للإصابات الجديدة
      affectedPopulation: 2700000, // عدد الحالات المصابة إجمالاً
    ),
    DiseaseStates(
      name: "Parkinson’s Disease",
      prevalence: "1-2% of people over 60 years old",
      regions: "Worldwide, higher in developed countries",
      causes: "Unclear, genetic and environmental factors",
      transmission: "Not contagious",
      prevalencePercent: 0.15,
      annualIncidence: 100000,
      affectedPopulation: 10000000,
    ),
    DiseaseStates(
      name: "Stroke",
      prevalence: "More than 13 million new cases annually worldwide",
      regions: "Global, higher in countries with unhealthy lifestyles",
      causes: "High blood pressure, smoking, diabetes, obesity",
      transmission: "Not contagious",
      prevalencePercent: null,
      annualIncidence: 13000000,
      affectedPopulation: 101000000, // تقدير الأشخاص المتأثرين
    ),
    DiseaseStates(
      name: "Down Syndrome",
      prevalence: "About 1 in 700 live births",
      regions: "Worldwide, not region-dependent",
      causes: "Genetic abnormality in chromosome 21",
      transmission: "Not contagious, genetic",
      prevalencePercent: 0.14,
      annualIncidence: 6000,
      affectedPopulation: 6000000,
    ),
    DiseaseStates(
      name: "Cystic Fibrosis",
      prevalence:
          "About 1 in 2500 to 3500 live births in people of European descent",
      regions: "Common in Europe and North America, rare in Asia",
      causes: "Genetic disorder",
      transmission: "Not contagious, genetic",
      prevalencePercent: 0.04,
      annualIncidence: 3000,
      affectedPopulation: 70000,
    ),
    DiseaseStates(
      name: "Muscular Dystrophies",
      prevalence:
          "Varies by type, e.g., Duchenne muscular dystrophy 1 in 3500-5000 male births",
      regions: "Worldwide",
      causes: "Genetic mutations causing progressive muscle weakness",
      transmission: "Not contagious, genetic",
      prevalencePercent: 0.02,
      annualIncidence: null,
      affectedPopulation: 250000,
    ),
    DiseaseStates(
      name: "Hearing Loss or Impairment",
      prevalence:
          "About 5% of the world population has some degree of hearing loss",
      regions: "Worldwide, higher in noisy environments",
      causes: "Genetic, infections, noise exposure, aging",
      transmission: "Not contagious",
      prevalencePercent: 5.0,
      annualIncidence: null,
      affectedPopulation: 430000000,
    ),
    DiseaseStates(
      name: "Visual Impairment or Blindness",
      prevalence: "About 2.2 billion people worldwide",
      regions: "Higher in countries with limited healthcare access",
      causes:
          "Congenital defects, chronic diseases like diabetes, injuries, aging",
      transmission: "Not contagious",
      prevalencePercent: 28.0,
      annualIncidence: null,
      affectedPopulation: 2200000000,
    ),
    DiseaseStates(
      name: "Speech and Communication Disorders",
      prevalence: "Affect about 7.5% of children",
      regions: "Worldwide",
      causes:
          "Multiple causes: cognitive disorders, language delay, neurological conditions",
      transmission: "Not contagious",
      prevalencePercent: 7.5,
      annualIncidence: null,
      affectedPopulation: null,
    ),
    DiseaseStates(
      name: "Autism Spectrum Disorder",
      prevalence: "About 1 in 100 children worldwide",
      regions: "Worldwide, increased diagnosis in developed countries",
      causes: "Complex genetic and environmental factors",
      transmission: "Not contagious",
      prevalencePercent: 1.0,
      annualIncidence: 700000,
      affectedPopulation: 70000000,
    ),
    DiseaseStates(
      name: "Attention Deficit Hyperactivity Disorder (ADHD)",
      prevalence: "About 5-7% of children",
      regions: "Worldwide",
      causes: "Genetic and environmental factors",
      transmission: "Not contagious",
      prevalencePercent: 6.0,
      annualIncidence: null,
      affectedPopulation: 60000000,
    ),
    DiseaseStates(
      name: "Depression and Anxiety Disorders",
      prevalence: "About 264 million people suffer from depression",
      regions: "Worldwide",
      causes: "Genetic, environmental, psychological, and social factors",
      transmission: "Not contagious",
      prevalencePercent: 3.4,
      annualIncidence: null,
      affectedPopulation: 264000000,
    ),
    DiseaseStates(
      name: "Schizophrenia",
      prevalence: "About 1% of the world population",
      regions: "Worldwide",
      causes: "Genetic and biological factors",
      transmission: "Not contagious",
      prevalencePercent: 1.0,
      annualIncidence: null,
      affectedPopulation: 80000000,
    ),
    DiseaseStates(
      name: "Diabetes",
      prevalence: "About 537 million adults worldwide",
      regions: "Global, higher in Western lifestyle countries",
      causes: "Genetics, unhealthy lifestyle, obesity",
      transmission: "Not contagious",
      prevalencePercent: 10.5,
      annualIncidence: 10000000,
      affectedPopulation: 537000000,
    ),
    DiseaseStates(
      name: "Hypertension and Heart Diseases",
      prevalence: "About 1.13 billion people have high blood pressure",
      regions: "Worldwide",
      causes: "Lifestyle, heredity, unhealthy diet, lack of physical activity",
      transmission: "Not contagious",
      prevalencePercent: 15.0,
      annualIncidence: null,
      affectedPopulation: 1130000000,
    ),
    DiseaseStates(
      name: "Learning Difficulties",
      prevalence: "Affect 5-15% of school-age children",
      regions: "Worldwide",
      causes: "Genetic, neurological, environmental factors",
      transmission: "Not contagious",
      prevalencePercent: 10.0,
      annualIncidence: null,
      affectedPopulation: null,
    ),
    DiseaseStates(
      name: "Speech Difficulties",
      prevalence: "About 5-10% of children",
      regions: "Worldwide",
      causes: "Neurological problems, developmental delay, other disorders",
      transmission: "Not contagious",
      prevalencePercent: 7.5,
      annualIncidence: null,
      affectedPopulation: null,
    ),
    DiseaseStates(
      name: "Intellectual Developmental Delay",
      prevalence: "About 1-3% of the population",
      regions: "Worldwide",
      causes: "Genetic factors, brain injury, malnutrition",
      transmission: "Not contagious",
      prevalencePercent: 2.0,
      annualIncidence: null,
      affectedPopulation: null,
    ),
  ],
  'ar': [
    DiseaseStates(
      name: "الشلل الدماغي",
      prevalence: "حوالي 2-3 لكل 1000 ولادة حية عالمياً",
      regions: "متساوي في الدول المتقدمة والنامية",
      causes:
          "إصابة الدماغ قبل أو أثناء أو بعد الولادة بفترة قصيرة (نقص أكسجين، عدوى، رضوض)",
      transmission: "غير معدي، ناتج عن تلف دماغي",
      prevalencePercent: 0.2,
      annualIncidence: 150000,
      affectedPopulation: 17000000,
    ),
    DiseaseStates(
      name: "التصلب اللويحي",
      prevalence: "أكثر شيوعاً في المناطق المعتدلة",
      regions: "شمال أوروبا، أمريكا الشمالية، أقل في المناطق الاستوائية",
      causes: "مرض مناعي ذاتي مع عوامل وراثية وبيئية (نقص فيتامين D)",
      transmission: "غير معدي",
      prevalencePercent: 0.1,
      annualIncidence: 25000,
      affectedPopulation: 2500000,
    ),
    DiseaseStates(
      name: "إصابات الحبل الشوكي",
      prevalence: "250-500 حالة جديدة لكل مليون نسمة سنوياً",
      regions:
          "تختلف حسب البلد، أكثر شيوعاً في المناطق التي تشهد حوادث طرق وإصابات رياضية",
      causes: "حوادث المرور، الإصابات الرياضية، السقوط",
      transmission: "غير معدي",
      prevalencePercent: null,
      annualIncidence: 180000,
      affectedPopulation: 2700000,
    ),
    DiseaseStates(
      name: "مرض باركنسون",
      prevalence: "1-2% من الأشخاص فوق 60 سنة",
      regions: "عالمي، أعلى في الدول المتقدمة",
      causes: "غير واضح، عوامل وراثية وبيئية",
      transmission: "غير معدي",
      prevalencePercent: 0.15,
      annualIncidence: 100000,
      affectedPopulation: 10000000,
    ),
    DiseaseStates(
      name: "السكتة الدماغية",
      prevalence: "أكثر من 13 مليون حالة جديدة سنوياً حول العالم",
      regions: "عالمي، أعلى في البلدان التي تنتشر فيها أنماط حياة غير صحية",
      causes: "ارتفاع ضغط الدم، التدخين، السكري، السمنة",
      transmission: "غير معدي",
      prevalencePercent: null,
      annualIncidence: 13000000,
      affectedPopulation: 101000000,
    ),
    DiseaseStates(
      name: "متلازمة داون",
      prevalence: "حوالي 1 من كل 700 ولادة حية",
      regions: "عالمي، لا يعتمد على المنطقة",
      causes: "خلل جيني في الصبغي 21",
      transmission: "غير معدي، وراثي",
      prevalencePercent: 0.14,
      annualIncidence: 6000,
      affectedPopulation: 6000000,
    ),
    DiseaseStates(
      name: "التليف الكيسي",
      prevalence:
          "حوالي 1 من كل 2500-3500 ولادة حية في السكان ذوي الأصل الأوروبي",
      regions: "شائع في أوروبا وأمريكا الشمالية، نادر في آسيا",
      causes: "اضطراب وراثي",
      transmission: "غير معدي، وراثي",
      prevalencePercent: 0.04,
      annualIncidence: 3000,
      affectedPopulation: 70000,
    ),
    DiseaseStates(
      name: "ضمور العضلات",
      prevalence:
          "تختلف حسب النوع، مثلاً ضمور العضلات دوشين 1 من كل 3500-5000 ولادة ذكر",
      regions: "عالمي",
      causes: "طفرات جينية تسبب ضعفاً عضلياً تدريجياً",
      transmission: "غير معدي، وراثي",
      prevalencePercent: 0.02,
      annualIncidence: null,
      affectedPopulation: 250000,
    ),
    DiseaseStates(
      name: "ضعف السمع أو فقدانه",
      prevalence: "حوالي 5% من سكان العالم يعانون من ضعف سمع",
      regions: "عالمي، أعلى في البيئات الصاخبة",
      causes: "وراثي، عدوى، تعرض للضوضاء، التقدم في العمر",
      transmission: "غير معدي",
      prevalencePercent: 5.0,
      annualIncidence: null,
      affectedPopulation: 430000000,
    ),
    DiseaseStates(
      name: "ضعف البصر أو العمى",
      prevalence: "حوالي 2.2 مليار شخص حول العالم",
      regions: "أعلى في البلدان ذات الرعاية الصحية المحدودة",
      causes: "عيوب خلقية، أمراض مزمنة مثل السكري، إصابات، تقدم في العمر",
      transmission: "غير معدي",
      prevalencePercent: 28.0,
      annualIncidence: null,
      affectedPopulation: 2200000000,
    ),
    DiseaseStates(
      name: "اضطرابات النطق والتواصل",
      prevalence: "تؤثر على حوالي 7.5% من الأطفال",
      regions: "عالمي",
      causes: "أسباب متعددة: اضطرابات معرفية، تأخر لغوي، حالات عصبية",
      transmission: "غير معدي",
      prevalencePercent: 7.5,
      annualIncidence: null,
      affectedPopulation: null,
    ),
    DiseaseStates(
      name: "اضطراب طيف التوحد",
      prevalence: "حوالي 1 من كل 100 طفل حول العالم",
      regions: "عالمي، زيادة التشخيص في الدول المتقدمة",
      causes: "عوامل وراثية وبيئية معقدة",
      transmission: "غير معدي",
      prevalencePercent: 1.0,
      annualIncidence: 700000,
      affectedPopulation: 70000000,
    ),
    DiseaseStates(
      name: "اضطراب نقص الانتباه مع فرط النشاط (ADHD)",
      prevalence: "حوالي 5-7% من الأطفال",
      regions: "عالمي",
      causes: "عوامل وراثية وبيئية",
      transmission: "غير معدي",
      prevalencePercent: 6.0,
      annualIncidence: null,
      affectedPopulation: 60000000,
    ),
    DiseaseStates(
      name: "الاكتئاب واضطرابات القلق",
      prevalence: "حوالي 264 مليون شخص يعانون من الاكتئاب",
      regions: "عالمي",
      causes: "عوامل وراثية وبيئية ونفسية واجتماعية",
      transmission: "غير معدي",
      prevalencePercent: 3.4,
      annualIncidence: null,
      affectedPopulation: 264000000,
    ),
    DiseaseStates(
      name: "الفصام",
      prevalence: "حوالي 1% من سكان العالم",
      regions: "عالمي",
      causes: "عوامل وراثية وبيولوجية",
      transmission: "غير معدي",
      prevalencePercent: 1.0,
      annualIncidence: null,
      affectedPopulation: 80000000,
    ),
    DiseaseStates(
      name: "داء السكري",
      prevalence: "حوالي 537 مليون بالغ حول العالم",
      regions: "عالمي، أكثر في الدول ذات نمط الحياة الغربي",
      causes: "وراثة، نمط حياة غير صحي، سمنة",
      transmission: "غير معدي",
      prevalencePercent: 10.5,
      annualIncidence: 10000000,
      affectedPopulation: 537000000,
    ),
    DiseaseStates(
      name: "ارتفاع ضغط الدم وأمراض القلب",
      prevalence: "حوالي 1.13 مليار شخص يعانون من ارتفاع ضغط الدم",
      regions: "عالمي",
      causes: "نمط حياة، وراثة، نظام غذائي غير صحي، نقص نشاط بدني",
      transmission: "غير معدي",
      prevalencePercent: 15.0,
      annualIncidence: null,
      affectedPopulation: 1130000000,
    ),
    DiseaseStates(
      name: "صعوبات التعلم",
      prevalence: "تؤثر على 5-15% من الأطفال في سن المدرسة",
      regions: "عالمي",
      causes: "عوامل وراثية، عصبية، بيئية",
      transmission: "غير معدي",
      prevalencePercent: 10.0,
      annualIncidence: null,
      affectedPopulation: null,
    ),
    DiseaseStates(
      name: "صعوبات الكلام",
      prevalence: "حوالي 5-10% من الأطفال",
      regions: "عالمي",
      causes: "مشاكل عصبية، تأخر في النمو، اضطرابات أخرى",
      transmission: "غير معدي",
      prevalencePercent: 7.5,
      annualIncidence: null,
      affectedPopulation: null,
    ),
    DiseaseStates(
      name: "تأخر النمو العقلي",
      prevalence: "حوالي 1-3% من السكان",
      regions: "عالمي",
      causes: "عوامل وراثية، إصابات دماغية، سوء تغذية",
      transmission: "غير معدي",
      prevalencePercent: 2.0,
      annualIncidence: null,
      affectedPopulation: null,
    ),
  ],
};
